AddonId: J-Hero_c0fabc1d-aadb-41e8-be6c-82e27147f6e4
Packages:
  - Version: 1.1
    RequiredApiVersion: 2.4.0
    ReleaseDate: 2023-02-01
    PackageUrl: https://github.com/Jhanlon95/J-Hero/releases/download/v1.0/J-Hero_c0fabc1d-aadb-41e8-be6c-82e27147f6e4_1_1.pthm
    Changelog:
          - Including Filter icons for Platforms or Sources
  - Version: 1.0
    RequiredApiVersion: 2.4.0
    ReleaseDate: 2023-02-01
    PackageUrl: https://github.com/Jhanlon95/J-Hero/releases/download/v1.0/J-Hero_c0fabc1d-aadb-41e8-be6c-82e27147f6e4_1_0.pthm
    Changelog:
          - Initial first release